<?php

namespace GravureBundle\Repository;

/**
 * BoxNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
