<?php

namespace GravureBundle\Repository;

/**
 * EndOfTheDayTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndOfTheDayTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
