<?php

namespace FaultyBundle\Repository;

/**
 * FaultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaultyRepository extends \Doctrine\ORM\EntityRepository
{
}
