<?php

namespace CM\EngravingBundle\Repository;


use Doctrine\ORM\EntityManager;
use CM\EngravingBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    /**
     * @return array|Category[]
     */
    public function findAll(){
        return $this->entityManager->getRepository('EngravingBundle:Category')->findAll();
    }


    public function findOneByIdProduct($id){
        return $this->entityManager->getRepository('EngravingBundle:Category')->findOneBy(['idProduct' => $id]);
    }

    public function save(Category $category){
        $this->entityManager->persist($category);
        $this->entityManager->flush();
    }

    public function delete(Category $category){
        $this->entityManager->remove($category);
        $this->entityManager->flush();
    }
    
}
