<?php

namespace CM\EngravingBundle\Repository;

/**
 * OrderRegulatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRegulatorRepository extends \Doctrine\ORM\EntityRepository
{
}
