<?php

namespace CM\ServiceClientBundle\Repository;

use Doctrine\ORM\EntityManager;
use CM\ServiceClientBundle\Entity\Attachment;
/**
 * AttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends \Doctrine\ORM\EntityRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    /**
     * @return array|Attachment[]
     */
    public function findAll(){
        return $this->entityManager->getRepository('ServiceClientBundle:Attachment')->findAll();
    }

    public function save(Attachment $attachment){
        $this->entityManager->persist($attachment);
        $this->entityManager->flush();
    }

    public function delete(Attachment $attachment){
        $this->entityManager->remove($attachment);
        $this->entityManager->flush();
    }
}
