<?php

namespace CM\ServiceClientBundle\Repository;

use Doctrine\ORM\EntityManager;
use CM\ServiceClientBundle\Entity\Bond;

/**
 * BondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BondRepository extends \Doctrine\ORM\EntityRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    /**
     * @return array|Bond[]
     */
    public function findAll(){
        return $this->entityManager->getRepository('ServiceClientBundle:Bond')->findAll();
    }

    public function save(Bond $bond){
        $this->entityManager->persist($bond);
        $this->entityManager->flush();
    }

    public function delete(Bond $bond){
        $this->entityManager->remove($bond);
        $this->entityManager->flush();
    }
}
