<?php

namespace CM\ServiceClientBundle\Repository;

/**
 * BondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BondRepository extends \Doctrine\ORM\EntityRepository
{
}
