<?php

namespace CM\ServiceClientBundle\Repository;

/**
 * Branch_childRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Branch_childRepository extends \Doctrine\ORM\EntityRepository
{
}
