<?php

namespace CM\ServiceClientBundle\Repository;

/**
 * MailBondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailBondRepository extends \Doctrine\ORM\EntityRepository
{
}
